### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wangl-cc** [MaaAssistantArknights/maa-cli#87]
This issue serves as a to-do list for the project, enumerating tasks I intend to tackle but haven't addressed yet. If you have any suggestions, feel free to leave comments here or open an issue. If you'd like to contribute, PRs are welcome.

### v0.6

- [ ] Split CLI into server and client components. There will be a RPC server listening on a Unix or TCP socket. Commands like `maa run`, `maa startup`, etc., will parse arguments and send requests to the server. By default, these commands will launch a server first and then send the RPC request. The server will persist for a while, allowing different tasks to run without reloading MaaCore. There will also be a command, `maa serve`, to launch servers manually. This RPC server can also be used for remote control or by other clients.

### v0.7

- [ ] Internationalization (i18n). Currently, help, log, and error messages are hard-coded in English. Incorporating an i18n framework will enable these messages to be displayed in other languages. [Early attempt](https://github.com/MaaAssistantArknights/maa-cli/tree/feat/i18n)

## TBD

This section is reserved for items that remain undecided. Please feel free to initiate discussions on these topics.

- [ ] Refactor the callback message parsing handler.
- [ ] Incorporate version compatibility checks for `MaaCore`. For instance, if a user wants to set static options, ensure their `MaaCore` version is greater than 4.26.0.

**Comment by wangl-cc** [comment]
Replaced with milestones.
